# Generated by Django 5.2 on 2025-04-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.PositiveSmallIntegerField()),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'bible_verses_kjv_strongs',
                'ordering': ['book', 'chapter', 'verse'],
                'managed': False,
            },
        ),
    ]
