# Generated by Django 5.2 on 2025-04-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0003_alter_bibleverse_table_versecomment_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('verse_number', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['verse_number'],
                'unique_together': {('book', 'chapter', 'verse_number')},
            },
        ),
    ]
