# Generated by Django 5.2 on 2025-04-24 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0004_verse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibleverse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'managed': False},
        ),
    ]
