# Generated by Django 5.2 on 2025-04-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0005_alter_bibleverse_options_alter_verse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibleverse',
            options={'managed': False, 'ordering': ['book', 'chapter', 'verse']},
        ),
        migrations.AlterModelTable(
            name='verse',
            table='bible_verses_kjv',
        ),
    ]
