# Generated by Django 5.2 on 2025-04-24 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0008_comment_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='color',
        ),
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend_app.group'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='book',
            field=models.CharField(default='Genesis', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='chapter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend_app.group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlight',
            name='verse',
            field=models.IntegerField(),
        ),
    ]
