# Generated by Django 5.2 on 2025-04-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0009_remove_highlight_color_comment_group_highlight_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='color',
            field=models.CharField(default='yellow', max_length=20),
        ),
        migrations.AddField(
            model_name='highlight',
            name='verse_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlight',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_app.bibleverse'),
        ),
    ]
