# Generated by Django 5.2 on 2025-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_app', '0010_highlight_color_highlight_verse_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='verse_number',
            field=models.IntegerField(default=1),
        ),
    ]
